//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Aeon.Foraging
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Creates a command to send to an underground feeder controller.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [System.ComponentModel.DescriptionAttribute("Creates a command to send to an underground feeder controller.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CreateFeederCommand
    {
    
        private FeederCommand _command;
    
        public CreateFeederCommand()
        {
            _command = FeederCommand.DeliverPellet;
        }
    
        protected CreateFeederCommand(CreateFeederCommand other)
        {
            _command = other._command;
        }
    
        /// <summary>
        /// The command to send to the feeder device.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The command to send to the feeder device.")]
        public FeederCommand Command
        {
            get
            {
                return _command;
            }
            set
            {
                _command = value;
            }
        }
    
        public System.IObservable<CreateFeederCommand> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CreateFeederCommand(this)));
        }
    
        public System.IObservable<CreateFeederCommand> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CreateFeederCommand(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Command = " + _command);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Specifies the type of command to send to an underground feeder controller.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    public enum FeederCommand
    {
    
        DeliverPellet = 0,
    
        ResetFeeder = 1,
    }


    /// <summary>
    /// Represents control and acquisition functionality for an underground feeder module.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [System.ComponentModel.DescriptionAttribute("Represents control and acquisition functionality for an underground feeder module" +
        ".")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UndergroundFeeder
    {
    
        private int _pelletDeliveryRetryCount;
    
        private double _pelletDeliveryTimeout;
    
        private double _wheelRadius;
    
        public UndergroundFeeder()
        {
            _pelletDeliveryRetryCount = 2;
            _pelletDeliveryTimeout = 1D;
            _wheelRadius = -4D;
        }
    
        protected UndergroundFeeder(UndergroundFeeder other)
        {
            _pelletDeliveryRetryCount = other._pelletDeliveryRetryCount;
            _pelletDeliveryTimeout = other._pelletDeliveryTimeout;
            _wheelRadius = other._wheelRadius;
        }
    
        /// <summary>
        /// The number of times to retry a failed pellet delivery.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The number of times to retry a failed pellet delivery.")]
        public int PelletDeliveryRetryCount
        {
            get
            {
                return _pelletDeliveryRetryCount;
            }
            set
            {
                _pelletDeliveryRetryCount = value;
            }
        }
    
        /// <summary>
        /// The amount of time in seconds to wait for pellet detection before reporting a failure.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The amount of time in seconds to wait for pellet detection before reporting a fai" +
            "lure.")]
        public double PelletDeliveryTimeout
        {
            get
            {
                return _pelletDeliveryTimeout;
            }
            set
            {
                _pelletDeliveryTimeout = value;
            }
        }
    
        /// <summary>
        /// The radius of the wheel, in centimeters.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The radius of the wheel, in centimeters.")]
        public double WheelRadius
        {
            get
            {
                return _wheelRadius;
            }
            set
            {
                _wheelRadius = value;
            }
        }
    
        public System.IObservable<UndergroundFeeder> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UndergroundFeeder(this)));
        }
    
        public System.IObservable<UndergroundFeeder> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UndergroundFeeder(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PelletDeliveryRetryCount = " + _pelletDeliveryRetryCount + ", ");
            stringBuilder.Append("PelletDeliveryTimeout = " + _pelletDeliveryTimeout + ", ");
            stringBuilder.Append("WheelRadius = " + _wheelRadius);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }
}