//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Aeon.Video
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Represents a FLIR Spinnaker camera acquisition module.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [System.ComponentModel.DescriptionAttribute("Represents a FLIR Spinnaker camera acquisition module.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SpinnakerCamera
    {
    
        private string _serialNumber;
    
        private double _exposureTime;
    
        private double _gain;
    
        private int _binning;
    
        public SpinnakerCamera()
        {
            _exposureTime = 1000D;
            _gain = 0D;
            _binning = 1;
        }
    
        protected SpinnakerCamera(SpinnakerCamera other)
        {
            _serialNumber = other._serialNumber;
            _exposureTime = other._exposureTime;
            _gain = other._gain;
            _binning = other._binning;
        }
    
        /// <summary>
        /// The serial number of the camera.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The serial number of the camera.")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        /// <summary>
        /// The exposure time of the sensor, in microseconds.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The exposure time of the sensor, in microseconds.")]
        public double ExposureTime
        {
            get
            {
                return _exposureTime;
            }
            set
            {
                _exposureTime = value;
            }
        }
    
        /// <summary>
        /// The camera gain.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The camera gain.")]
        public double Gain
        {
            get
            {
                return _gain;
            }
            set
            {
                _gain = value;
            }
        }
    
        /// <summary>
        /// The camera binning configuration.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The camera binning configuration.")]
        public int Binning
        {
            get
            {
                return _binning;
            }
            set
            {
                _binning = value;
            }
        }
    
        public System.IObservable<SpinnakerCamera> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SpinnakerCamera(this)));
        }
    
        public System.IObservable<SpinnakerCamera> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SpinnakerCamera(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("SerialNumber = " + _serialNumber + ", ");
            stringBuilder.Append("ExposureTime = " + _exposureTime + ", ");
            stringBuilder.Append("Gain = " + _gain + ", ");
            stringBuilder.Append("Binning = " + _binning);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }
}