//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Aeon.Ephys
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Represents the configuration of the electrophysiology acquisition system.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [System.ComponentModel.DescriptionAttribute("Represents the configuration of the electrophysiology acquisition system.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class EphysConfiguration
    {
    
        private OpenEphys.Onix1.ConfigureNeuropixelsV2PsbDecoder _neuropixelsV2Decoder;
    
        public EphysConfiguration()
        {
        }
    
        protected EphysConfiguration(EphysConfiguration other)
        {
            _neuropixelsV2Decoder = other._neuropixelsV2Decoder;
        }
    
        /// <summary>
        /// The configuration of the Neuropixels v2 decoder module.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DescriptionAttribute("The configuration of the Neuropixels v2 decoder module.")]
        public OpenEphys.Onix1.ConfigureNeuropixelsV2PsbDecoder NeuropixelsV2Decoder
        {
            get
            {
                return _neuropixelsV2Decoder;
            }
            set
            {
                _neuropixelsV2Decoder = value;
            }
        }
    
        public System.IObservable<EphysConfiguration> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new EphysConfiguration(this)));
        }
    
        public System.IObservable<EphysConfiguration> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new EphysConfiguration(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("NeuropixelsV2Decoder = " + _neuropixelsV2Decoder);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }
}